sudo: required
language: node_js

cache:
  directories:
    - node_modules

dist: trusty

jobs:
  include:
    - stage: release
      if: branch = master
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release